ITEM.name = "20 Gauage Ammo"
ITEM.desc = "A box of 50 rounds used for some shotguns. Ammmo may not save after use."
ITEM.entdrop = "20gaugeammo"
ITEM.model = "models/visualitygaming/fallout/ammo/20gauge.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1