ITEM.name = ".32 Ammo"
ITEM.desc = "A box of 100 rounds used for certain revolvers. Ammmo may not save after use."
ITEM.entdrop = "32ammo"
ITEM.model = "models/visualitygaming/fallout/ammo/32cal.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1