ITEM.name = ".357 Ammo"
ITEM.desc = "A box of 50 rounds used for certain revolvers. Ammmo may not save after use."
ITEM.entdrop = "357magnumammo"
ITEM.model = "models/visualitygaming/fallout/ammo/357.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1