ITEM.name = ".45 Auto Ammo"
ITEM.desc = "A box of 50 rounds used for certain pistols. Ammmo may not save after use."
ITEM.entdrop = "45autoammo"
ITEM.model = "models/visualitygaming/fallout/ammo/45cal.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1