ITEM.name = "40mm Grenade Rounds"
ITEM.desc = "A box of 5 grenades used for some launchers. Ammmo may not save after use."
ITEM.entdrop = "halo_ammo_40mm"
ITEM.model = "models/visualitygaming/fallout/ammo/ammobox.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1