ITEM.name = "5mm Ammo"
ITEM.desc = "A box of 100 rounds used for some heavy weapons. Ammmo may not save after use."
ITEM.entdrop = "5mmammo"
ITEM.model = "models/mosi/fallout4/ammo/5mm.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1