ITEM.name = "Darts"
ITEM.desc = "A box of 100 rounds used for some heavy weapons. Ammmo may not save after use."
ITEM.entdrop = "darts"
ITEM.model = "models/visualitygaming/fallout/ammo/ammobox.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1