ITEM.name = "Mini-Nuke"
ITEM.desc = "A single miniature nuke used for the Fat Man launcher. Ammmo may not save after use."
ITEM.entdrop = "mininuke"
ITEM.model = "models/mosi/fallout4/ammo/mininuke.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1