ITEM.name = "Missles"
ITEM.desc = "A box of a few missles. Ammmo may not save after use."
ITEM.entdrop = "missiles"
ITEM.model = "models/mosi/fallout4/ammo/missile.mdl"
ITEM.price = 0
ITEM.category = "Ammunition"
ITEM.flag = "A"
ITEM.width = 1
ITEM.height = 1