ITEM.name = "Assault Carbine"
ITEM.desc = "Uses 5.56mm rounds. The assault carbine is a magazine-fed, compact automatic weapon with a high rate of fire and a comparatively low spread."
ITEM.model = "models/halokiller38/fallout/weapons/assaultrifles/assaultcarbine.mdl"
ITEM.class = "weapon_assaultcarbine"
ITEM.weaponCategory = "assault"
ITEM.flag = "a"
ITEM.category = "Assault Weapons"
ITEM.width = 4
ITEM.height = 2