ITEM.name = "Marksman Carbine - Extended Magazine"
ITEM.desc = "Uses 5.56mm rounds. Filling in the gap between regular assault rifles and sniper rifles, the marksman rifle is designed for infantrymen deployed in the designated marksman role. It is built on the assault carbine platform, as an air-cooled, gas-operated rifle, with a rotating bolt, actuated by direct impingement gas operation. However, to better fit its tactical role, it is optimized for accuracy, rather than rate of fire. It features a precision adjustable stock, a tactical rail accessory system in place of the top receiver, typically with a 2.86x telescopic sight mounted on top, and fires in semi-automatic mode only, from a 20-round 5.56mm round magazine."
ITEM.model = "models/halokiller38/fallout/weapons/assaultrifles/marksmancarbineext.mdl"
ITEM.class = "weapon_marksmancarbinesil"
ITEM.weaponCategory = "assault"
ITEM.flag = "a"
ITEM.category = "Assault Weapons"
ITEM.width = 4
ITEM.height = 2