ITEM.name = "R91 Assault Rifle"
ITEM.desc = "Uses 5.56mm rounds. Manufactured by civilian defense contractor Stent Security Solutions, the R91 assault rifle is a conventional design chambered for 5.56mm ammunition. Employing a roller delayed blowback system, it is a very sturdy design, with simple iron sights that consist of a rotary rear drum and hooded front post, a fire selector switch with three settings (safe, fully automatic fire, single shot), and a flash suppressor. The final touch is the wooden stock and handguard."
ITEM.model = "models/halokiller38/fallout/weapons/assaultrifles/r91assaultrifle.mdl"
ITEM.class = "weapon_r91assaultrifle"
ITEM.weaponCategory = "assault"
ITEM.flag = "a"
ITEM.category = "Assault Weapons"
ITEM.width = 4
ITEM.height = 2