ITEM.name = "Combat Knife"
ITEM.desc = "This military-issue cutting tool was designed for more than saw-ing rope. The combat knife tears through flesh, too, but it can't pierce strong armor."
ITEM.model = "models/halokiller38/fallout/weapons/melee/combatknife.mdl"
ITEM.class = "weapon_combatknife"
ITEM.weaponCategory = "blade"
ITEM.flag = "b"
ITEM.category = "Bladed Weapons"
ITEM.width = 1
ITEM.height = 1