ITEM.name = "Rolling Pin"
ITEM.desc = "A simple wooden rolling pin. It has a medium swing speed with alternating vertical and horizontal strikes. Its power attack is a heavy downward blow."
ITEM.model = "models/halokiller38/fallout/weapons/melee/rollingpin.mdl"
ITEM.class = "weapon_rollingpin"
ITEM.weaponCategory = "blunt"
ITEM.flag = "B"
ITEM.category = "Blunt Weapons"
ITEM.width = 1
ITEM.height = 1