ITEM.name = "Pool Cue"
ITEM.desc = "This weapon may serve well in the earliest parts of the game as the player's first foes are weak. But this weapon becomes useless, to say the least, in other parts of the game. Due to its low damage, it can be easily replaced when compared to other 2-handed melee weapons, such as the nail board or the baseball bat which can be found early in the game."
ITEM.model = "models/halokiller38/fallout/weapons/melee/poolcue.mdl"
ITEM.class = "weapon_poolcue"
ITEM.weaponCategory = "blunt"
ITEM.flag = "B"
ITEM.category = "Blunt Weapons"
ITEM.width = 1
ITEM.height = 3