ITEM.name = "Hatchet"
ITEM.desc = "It is a hand-axe with a rubber-gripped wooden handle for chopping wood and limbs alike. Unlike throwing hatchets, these are not balanced for use as a projectile weapon."
ITEM.model = "models/halokiller38/fallout/weapons/melee/hatchet.mdl"
ITEM.class = "weapon_hatchet"
ITEM.weaponCategory = "blade"
ITEM.flag = "b"
ITEM.category = "Bladed Weapons"
ITEM.width = 1
ITEM.height = 1