ITEM.name = "Old Glory"
ITEM.desc = "Old Glory is the signature weapon of Ulysses. It is a maple flag pole capped with a golden eagle."
ITEM.model = "models/halokiller38/fallout/weapons/melee/eagleflagpoll.mdl"
ITEM.class = "weapon_eagleflagpole"
ITEM.weaponCategory = "blunt"
ITEM.flag = "B"
ITEM.category = "Blunt Weapons"
ITEM.width = 1
ITEM.height = 3