ITEM.name = "Katana"
ITEM.desc = "A katana is a type of Japanese sword with a blade length greater than 23.6-28.7 inches (60-73 centimeters) and characterized by its distinctive appearance: a curved, slender, single-edged blade, circular or squared guard, and long grip that can accommodate two hands. Often called a samurai sword or samurai's sword because of its use by the feudal warriors, it became a symbol of the samurai caste."
ITEM.model = "models/halokiller38/fallout/weapons/melee/katana.mdl"
ITEM.class = "weapon_katana"
ITEM.weaponCategory = "blade"
ITEM.flag = "b"
ITEM.category = "Bladed Weapons"
ITEM.width = 1
ITEM.height = 3