ITEM.name = "Gun Runner's Baseball Bat"
ITEM.desc = "The baseball bat (GRA) is specially designed by the Gun Runners to accept modifications, which the standard variant cannot."
ITEM.model = "models/halokiller38/fallout/weapons/melee/baseballbat.mdl"
ITEM.class = "weapon_bballbatclean"
ITEM.weaponCategory = "blunt"
ITEM.flag = "B"
ITEM.category = "Blunt Weapons"
ITEM.width = 1
ITEM.height = 2