ITEM.name = "Trench Knife"
ITEM.desc = "The trench knife is a combat knife designed to kill or gravely incapacitate an enemy soldier at close quarters. It was developed in response to a need for a close combat weapon for soldiers conducting assaults and raids on enemy trenchlines during the First World War. This particular model was used by American soldiers during the Anchorage Reclamation."
ITEM.model = "models/halokiller38/fallout/weapons/melee/trenchknife.mdl"
ITEM.class = "weapon_trenchknife"
ITEM.weaponCategory = "blade"
ITEM.flag = "b"
ITEM.category = "Bladed Weapons"
ITEM.width = 1
ITEM.height = 1