ITEM.name = "Proton Axe"
ITEM.desc = "The proton axe resembles a futuristic war-axe with a glowing blue blade of electrical energy at its head. On the other side it has two capacitors which also share the same blue electric current. It does electrical damage with extra damage against robots and power armor users. It can be repaired with the inexpensive proton throwing axe, raising its resell value drastically."
ITEM.model = "models/halokiller38/fallout/weapons/melee/protonaxe.mdl"
ITEM.class = "weapon_protonaxe"
ITEM.weaponCategory = "blade"
ITEM.flag = "b"
ITEM.category = "Bladed Weapons"
ITEM.width = 1
ITEM.height = 3