ITEM.name = "Baseball Bat"
ITEM.desc = "This is a long, smooth wooden bat, typically made of ash, for use in the sport of baseball. Under MLB regulations, a baseball bat cannot exceed 2.61 inches in diameter at the widest point, can be no longer than 42 inches, and must be a single solid piece."
ITEM.model = "models/halokiller38/fallout/weapons/melee/baseballbatdirty.mdl"
ITEM.class = "weapon_bballbatdirty"
ITEM.weaponCategory = "blunt"
ITEM.flag = "B"
ITEM.category = "Blunt Weapons"
ITEM.width = 1
ITEM.height = 2