ITEM.name = "Plasma Defender"
ITEM.desc = "Uses energy cells. The Austrian made Glock 86 plasma pistol (also referred to as the Plasma Defender[1]), was designed before the Great War by the Gaston Glock artificial intelligence. It shoots a small bolt of superheated plasma, and is powered by a small energy cell."
ITEM.model = "models/halokiller38/fallout/weapons/plasma weapons/plasmadefender.mdl"
ITEM.class = "weapon_plasmadefender"
ITEM.weaponCategory = "energy"
ITEM.flag = "L"
ITEM.category = "Energy Weapons"
ITEM.width = 2
ITEM.height = 1