ITEM.name = "Gatling Laser"
ITEM.desc = "Uses electron charge packs. The Gatling laser has more damage and accuracy than a tri-barrel minigun, so this is a viable choice should one desire more accuracy and damage per magazine. Its ammo is considerably more cost efficient than a minigun's, so this is also good for player characters on a budget that doesn't accommodate for 5mm rounds, but makes fusion cores affordable."
ITEM.model = "models/halokiller38/fallout/weapons/energy weapons/gatlinglaser.mdl"
ITEM.class = "weapon_gatlinglaser"
ITEM.weaponCategory = "energy"
ITEM.flag = "L"
ITEM.category = "Energy Weapons"
ITEM.width = 5
ITEM.height = 3