ITEM.name = "Laser Rifle w/ Scope and Beam Splitter"
ITEM.desc = "Uses microfusion cells. Several different models exist, from low power home-made versions to extremely powerful military weapons. As with all energy weapons, laser rifles can suffer from poor performance if not properly maintained. The crystal arrays and non-mechanical components are delicate and if not properly serviced can lead to a loss of beam intensity, overheating, and energy regulation failure. Given that laser weapons were still in their infancy as regular military weapons, parts can be hard to come by in the wasteland. However, their lack of moving parts (aside from the microfusion cell holding latch and trigger mechanism) means they are resilient against extended use."
ITEM.model = "models/halokiller38/fallout/weapons/energy weapons/laserriflescopebs.mdl"
ITEM.class = "weapon_laserriflebsscp"
ITEM.weaponCategory = "energy"
ITEM.flag = "L"
ITEM.category = "Energy Weapons"
ITEM.width = 4
ITEM.height = 2