ITEM.name = "LAER"
ITEM.desc = "Uses microfusion cells. The LAER resembles a mix of many existing energy weapons; the barrel looks like the pulse gun, the microfusion cell is held in a basket on the bottom like a plasma rifle, the stock is similar to a laser rifle, and it displays vacuum tubes similar to a recharger rifle. It also offers very high damage (on par with the plasma caster) for low ammunition consumption making it a great all around weapon."
ITEM.model = "models/halokiller38/fallout/weapons/energy weapons/laer.mdl"
ITEM.class = "weapon_laer"
ITEM.weaponCategory = "energy"
ITEM.flag = "L"
ITEM.category = "Energy Weapons"
ITEM.width = 4
ITEM.height = 2