ITEM.name = "Frag Mine"
ITEM.desc = "The frag mine is a placed explosive device. When approached by an enemy it emits a beep shortly before exploding. It can be disarmed while close to it by interacting with it."
ITEM.model = "models/halokiller38/fallout/weapons/mines/minefrag.mdl"
ITEM.class = "weapon_minefrag"
ITEM.weaponCategory = "explosive"
ITEM.flag = "X"
ITEM.category = "Explosives"
ITEM.width = 1
ITEM.height = 1