ITEM.name = "Frag Grenade"
ITEM.desc = "Frag grenades are muscle-propelled explosives. Fragmentation grenades are pretty rare, and are not too useful late game, when most enemies have a very high explosive damage resistance. If a few can be found early on, they can cause great peril for weaker raiders and critters. Ideally, the blast radius of a grenade should be used against large groups, like mantises and golden geckos, to maximize a single grenade's damage potential."
ITEM.model = "models/halokiller38/fallout/weapons/explosives/fraggrenade.mdl"
ITEM.class = "weapon_grenadefrag"
ITEM.weaponCategory = "explosive"
ITEM.flag = "X"
ITEM.category = "Explosives"
ITEM.width = 1
ITEM.height = 1