ITEM.name = "Automatic Rifle"
ITEM.desc = "Uses .308 rounds. The automatic rifle is a powerful support weapon firing .308 caliber rounds. The weapon holds 20 rounds in a box magazine, has a higher base damage per shot than any other fully-automatic projectile weapon and a comparatively high critical chance."
ITEM.model = "models/halokiller38/fallout/weapons/heavy weapons/automaticrifle.mdl"
ITEM.class = "weapon_automaticrifle"
ITEM.weaponCategory = "heavy"
ITEM.flag = "H"
ITEM.category = "Heavy Weapons"
ITEM.width = 5
ITEM.height = 2