ITEM.name = "Minigun"
ITEM.desc = "Uses 5mm rounds. A minigun is a multi-barrel machine gun with a high rate of fire, employing Gatling-style rotating barrels. It was a standard military weapon before the Great War, with Rockwell's CZ series being the most popular choice in the United States."
ITEM.model = "models/halokiller38/fallout/weapons/heavy weapons/minigun.mdl"
ITEM.class = "weapon_minigun"
ITEM.weaponCategory = "heavy"
ITEM.flag = "H"
ITEM.category = "Heavy Weapons"
ITEM.width = 5
ITEM.height = 3