ITEM.name = ".22 Silenced Pistol"
ITEM.desc = "Uses .22 rounds. The silenced .22 pistol is a .22LR round handgun with an integrated silencer. It's classified as a silent weapon, and can be used to attack targets without alerting nearby creatures or NPCs to the player's presence."
ITEM.model = "models/halokiller38/fallout/weapons/pistols/silenced22pistol.mdl"
ITEM.class = "weapon_22mmpistolsil"
ITEM.weaponCategory = "pistol"
ITEM.flag = "P"
ITEM.category = "Pistol Weapons"
ITEM.width = 2
ITEM.height = 1