ITEM.name = "9mm Pistol w/ Extended Clip and Scope"
ITEM.desc = "Uses 9mm rounds. The M&A 9mm pistol is a semi-automatic handgun, designed by M&A Guns Manufacturers. It is the standard issue sidearm of the New California Republic Army and a common sight in the Mojave Wasteland."
ITEM.model = "models/halokiller38/fallout/weapons/pistols/9mmextclipscp.mdl"
ITEM.class = "weapon_9mmpistolextscp"
ITEM.weaponCategory = "pistol"
ITEM.flag = "P"
ITEM.category = "Pistol Weapons"
ITEM.width = 2
ITEM.height = 1