ITEM.name = "10mm Pistol w/ Extended Grip"
ITEM.desc = "Uses 10mm rounds. 10mm pistols are sidearms using the 10mm ammunition that was common before the Great War. They were used extensively by the Bureau of Alcohol, Drugs, Tobacco, Firearms and Lasers, while in the military such pistols were being phased out in favor of energy weapons.[1] Their ruggedness, reliability, and firepower made them a popular choice among wastelanders and thus a staple of wasteland firefights."
ITEM.model = "models/halokiller38/fallout/weapons/pistols/10mmpistolextendedmag.mdl"
ITEM.class = "weapon_10mmpistolext"
ITEM.weaponCategory = "pistol"
ITEM.flag = "P"
ITEM.category = "Pistol Weapons"
ITEM.width = 2
ITEM.height = 1