ITEM.name = "T-45b"
ITEM.desc = "Developed before the Great War, the T-45 was originally developed and manufactured for the United States Army by American defense contractor West Tek. The T-45 power armor was the first version of power armor to be successfully deployed in battle, and as such, it remains relatively common more than 200 years later."
ITEM.model = "models/llama/briefcasedopen.mdl"
ITEM.width = 3
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.flag = "f"
ITEM.category = "Outfits"
ITEM.replacements = "models/power_armor/t45b.mdl"
