ITEM.name = "T-45d"
ITEM.desc = "While the T-45d armor is similar in its overall shape to the newer T-51b power armor, it is significantly less advanced than its later counterpart, and uses riveted steel plates instead of plastic composite materials in its construction. Various electronic and mechanical subsystems of the armor are exposed on the outside of its casing rather than sealed within as in the T-51b, making it far more susceptible to damage. In addition, a specialized body suit is required to be worn underneath the T-45d's armored shell in order to facilitate linking the armor's servos to the wearer's own motions and to make the armor more bearable because of its heat dissipation problems."
ITEM.model = "models/llama/briefcasedopen.mdl"
ITEM.width = 3
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.flag = "f"
ITEM.category = "Outfits"
ITEM.replacements = "models/power_armor/t45d.mdl"
