ITEM.name = "T-51b"
ITEM.desc = "T-51b powered infantry armor, or power armor, represented the peak of armored infantry technology before the Great War. Developed in the laboratories of the West Tek Research Facility,[1] the T-51b was deployed at the end of the Anchorage Reclamation, and by January 2077, the armor had become standard issue for American soldiers in the Army's Mechanized Cavalry Regiments. Now, only the most technologically advanced factions with ties to the pre-Great War American military or federal government, such as the Brotherhood of Steel or the Enclave, have access to this type of power armor."
ITEM.model = "models/llama/briefcasedopen.mdl"
ITEM.width = 3
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.flag = "f"
ITEM.category = "Outfits"
ITEM.replacements = "models/t51b/t51b.mdl"
