ITEM.name = "T-51e"
ITEM.desc = "T-51 was the most advanced power armor in wide-scale use before the outbreak of the Great War. First seeing service - and inherently, great success - in the Anchorage Reclamation campaign, the T-51 power armor soon became standard issue for the army's armored infantry regiments. Developed at the West Tek research facility, the T-51 was the peak of pre-War power armor technology. It saw continuous service throughout the Great War, and is thought to be the force that drove the Chinese out of Anchorage."
ITEM.model = "models/llama/briefcasedopen.mdl"
ITEM.width = 3
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.flag = "f"
ITEM.category = "Outfits"
ITEM.replacements = "models/t51b/t51e.mdl"
